import { Province } from "./Province";

export type Stagiaire = {
  id?: number | null;
  nom?: string | null;
  prenom?: string | null;
  dateNaissance?: string | null;
  adresse?: string | null;
  situationFamilial?: string | null;
  cin?: string | null;
  email?: string | null;
  nomUniversite?: string | null;
  adresseUniversite?: string | null;
  specialite?: string | null;
  assure?: boolean | null;
  attestationsAssurance?: File | null;
  fileNameAssurance?: string | null;
  fileTypeAssurance?: string | null;
  dateDebut1?: string | null;
  dateFin1?: string | null;
  province1?: Province | null;
  dateDebut2?: string | null;
  dateFin2?: string | null;
  province2?: Province | null;
  dateDebut3?: string | null;
  dateFin3?: string | null;
  province3?: Province | null;
  demande?: File | null;
  fileNameDemande?: string | null;
  fileTypeDemande?: string | null;
};
